apiVersion: v1
kind: Service
metadata:
  name: express-cloud-subservice
spec:
  selector:
    app: express-cloud-subservice
  type: LoadBalancer 
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
      nodePort: 31001