apiVersion: apps/v1
kind: Deployment
metadata:
  name: express-deployment-subservice
spec:
  selector:
    matchLabels:
      app: express-cloud-subservice
  template:
    metadata:
      labels:
        app: express-cloud-subservice
    spec:
      containers:
      - name: express-cloud-subservice
        image: express-cloud-subservice
        imagePullPolicy: Never
        ports:
            - containerPort: 3001
      restartPolicy: Always